In [1]:
import numpy as np

In [4]:
a=np.array([1,2,3,4,5,6])               # create array
b=np.array([[1,2,3],[4,5,6]])
print(a)
print(b)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [5]:
a=np.array([[1,2,3],[4,5,6]])          # sum to array
print(a.sum())

21


In [6]:
a=[[1,2],[3,4]]      #mutiplication to 2 array
b=[[5,6],[7,8]]
mul=np.dot(a,b)
print(mul)

[[19 22]
 [43 50]]


In [7]:
A = [[1, 2], [2, 3]]         # additon into 2 array
B = [[4, 5], [6, 7]]
ad=np.add(A,B)
print("addition :")
print(ad)

addition :
[[ 5  7]
 [ 8 10]]


In [8]:
a=np.array([[1,2,3],[4,5,6]])                # format to array
print("shape of a {}".format(a.shape))

shape of a (2, 3)


In [9]:
a=np.array([[1,2,3],[4,5,6]])                  # ndim
print("ndim {}".format(a.ndim))

ndim 2


In [11]:
a=np.array([[1,2,3],[4,5,6],[4,5,6]])       # array size
print("size {}".format(a.size))

size 9


In [12]:
a=np.array([[1,2,3],[4,5,6]])           # data type array
print("dtype {}".format(a.dtype))

dtype int64


In [13]:
a=np.array([[1,2,3],[4,5,6]])       # item size
print("itemsize {}".format(a.itemsize))

itemsize 8


In [14]:
a=np.array([[1,2,3],[4,5,6]])           # data memory
print("data {}".format(a.data))

data <memory at 0x7fd07c73b1e0>


In [16]:
a=np.array([1,2,3,4,5,6])           # reshape to 2 row and 3 column
re=a.reshape(2,3)
print(re)



[[1 2 3]
 [4 5 6]]


In [17]:
a=np.array([1,2,3,4,5,6])         # maximum number array
print("maximum is ",a.max())

maximum is  6


In [18]:
a=np.array([1,2,3,4,5,6])           # minimum number array
print("minimum is ",a.min())

minimum is  1


In [19]:
re=np.array([[1,2,3],[4,5,6]])               # maximum number to 2 array
print("maximum is ",re.max(axis=1))

maximum is  [3 6]


In [21]:
re=np.array([[1,2,3],[4,5,6]])               # minimum number to 2 array
print("maximum is ",re.min(axis=0))

maximum is  [1 2 3]


In [22]:
re=np.array([[1,4,9],[16,25,36]])           # squareroot of array value
print(np.sqrt(re))

[[1. 2. 3.]
 [4. 5. 6.]]


In [23]:
re=np.array([[1,4,9],[16,25,36]])            # standard deviation of array value
print("standard deviation ",np.std(re))

standard deviation  12.212243401148248


In [25]:
a=np.array([[1,2],[4,5]])     # print two array in vertically format
b=np.array([[8,7],[5,4]])
v=np.vstack((a,b))
print("vertical :")
print(v)

vertical :
[[1 2]
 [4 5]
 [8 7]
 [5 4]]


In [26]:
a=np.array([[1,2],[4,5]])           # print two array in horizontally format
b=np.array([[8,7],[5,4]])
h=np.hstack((a,b))
print("horizontal :")
print(h)

horizontal :
[[1 2 8 7]
 [4 5 5 4]]


In [28]:
a=np.arange(0,20,2)            # print even number 
print(a)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [29]:
a=np.linspace(0,20,11)      # space in your array
print(a)
print("data type: ",a.dtype)

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]
data type:  float64


In [30]:
a=np.array([[1,2],[4,5]])       
b=np.array([[8,7],[5,4]])
h=np.hstack((a,b))
ht=h.T         # convert into Row to Column and Column to Row
print(ht)

[[1 4]
 [2 5]
 [8 5]
 [7 4]]


In [31]:
for i in np.nditer(ht):            # show each elemnent or value
    print("ele :",i)

ele : 1
ele : 2
ele : 8
ele : 7
ele : 4
ele : 5
ele : 5
ele : 4


In [32]:
a=np.array([[1,2],[4,5]])
b=np.array([[8,7],[5,4]])
h=np.hstack((a,b))
h1=np.hsplit(h,2)       # split into horizontally format
print(h1)

[array([[1, 2],
       [4, 5]]), array([[8, 7],
       [5, 4]])]


In [33]:
a=np.array([[1,2],[4,5]])
b=np.array([[8,7],[5,4]])
h=np.vstack((a,b))
h1=np.vsplit(h,2)        # split into vertically format
print(h1)

[array([[1, 2],
       [4, 5]]), array([[8, 7],
       [5, 4]])]


In [34]:
from scipy import stats as st     # specify for the mean
a1=np.mean(a)
print(a1)

3.0


In [35]:
from scipy import stats as st     # specify for the median
a1=np.median(a)
print(a1)

3.0


In [36]:
from scipy import stats as st     # specify for the mode
a1=st.mode(a)
print(a1)

ModeResult(mode=array([[1, 2]]), count=array([[1, 1]]))
